//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharepointMessenger {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharepointMessenger.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Conversation Folder {0} already exists..
        /// </summary>
        internal static string ConversationAlreadyExists {
            get {
                return ResourceManager.GetString("ConversationAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AssociatedUsers.
        /// </summary>
        internal static string ConversationKey {
            get {
                return ResourceManager.GetString("ConversationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error sending your message. Please try again..
        /// </summary>
        internal static string CreateChatMessageError {
            get {
                return ResourceManager.GetString("CreateChatMessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error. If this happens again please contact the site administrator..
        /// </summary>
        internal static string GeneralException {
            get {
                return ResourceManager.GetString("GeneralException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load contacts at this time..
        /// </summary>
        internal static string GetContactsError {
            get {
                return ResourceManager.GetString("GetContactsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not load messages at this time..
        /// </summary>
        internal static string GetMessagesError {
            get {
                return ResourceManager.GetString("GetMessagesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error creating the group..
        /// </summary>
        internal static string GroupCreateError {
            get {
                return ResourceManager.GetString("GroupCreateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Chat Messages list was not found in the {0} web..
        /// </summary>
        internal static string ListNotFound {
            get {
                return ResourceManager.GetString("ListNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharepoint Messenger.
        /// </summary>
        internal static string LoggingCategory {
            get {
                return ResourceManager.GetString("LoggingCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Message.
        /// </summary>
        internal static string SMUChatMessage {
            get {
                return ResourceManager.GetString("SMUChatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SMUGroupDescription {
            get {
                return ResourceManager.GetString("SMUGroupDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharepoint Messenger Group.
        /// </summary>
        internal static string SMUGroupName {
            get {
                return ResourceManager.GetString("SMUGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hold all chat messages for Sharepoint Messenger.
        /// </summary>
        internal static string SMUListDescription {
            get {
                return ResourceManager.GetString("SMUListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Messages.
        /// </summary>
        internal static string SMUListName {
            get {
                return ResourceManager.GetString("SMUListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharepoint Messenger View.
        /// </summary>
        internal static string SMUListViewName {
            get {
                return ResourceManager.GetString("SMUListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SMUPermissionDescription {
            get {
                return ResourceManager.GetString("SMUPermissionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharepoint Messenger User.
        /// </summary>
        internal static string SMUPermissionName {
            get {
                return ResourceManager.GetString("SMUPermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The web service could not validate your request..
        /// </summary>
        internal static string UserNotValidated {
            get {
                return ResourceManager.GetString("UserNotValidated", resourceCulture);
            }
        }
    }
}
